//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPlan
    {
        public int ActionPlanID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Actions_Morning { get; set; }
        public string Actions_Noon { get; set; }
        public string Actions_Afternoon { get; set; }
        public string Actions_Eve { get; set; }
        public int PatientPersonID { get; set; }
        public int CaregiverPersonID { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Caregiver Caregiver { get; set; }
    }
}
