//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using CommonInterfaces;

namespace DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bio : IDataBaseConform
    {
        public int BioID { get; set; }
        public string School { get; set; }
        public string Training { get; set; }
        public string University { get; set; }
        public string Job { get; set; }
        public string Partnership { get; set; }
        public string Children { get; set; }
        public string Leisure { get; set; }
        public string Family_Members { get; set; }
        public string Languages { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
