//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using CommonInterfaces;

namespace DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareReport : IDataBaseConform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CareReport()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int CareReportID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool ActionPlanFulfilled { get; set; }
        public string Deviations { get; set; }
        public int CaregiverPersonID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
        public virtual Caregiver Caregiver { get; set; }
    }
}
