//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaringRelatives
    {
        public int CaringRelativesID { get; set; }
        public string Name { get; set; }
        public bool LivesInHousehold { get; set; }
        public string VisitFrequency { get; set; }
        public string Activity { get; set; }
        public int PatientPersonID { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
