//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmbulantCareDBContainer : DbContext
    {
        public AmbulantCareDBContainer()
            : base("name=AmbulantCareDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> PersonSet { get; set; }
        public virtual DbSet<Bio> BioSet { get; set; }
        public virtual DbSet<Home> HomeSet { get; set; }
        public virtual DbSet<CaringRelatives> CaringRelativesSet { get; set; }
        public virtual DbSet<HealthData> HealthDataSet { get; set; }
        public virtual DbSet<Hospitaliations> HospitaliationsSet { get; set; }
        public virtual DbSet<VitalParameters> VitalParametersSet { get; set; }
        public virtual DbSet<RiskValues> RiskValuesSet { get; set; }
        public virtual DbSet<Medication> MedicationSet { get; set; }
        public virtual DbSet<CareReport> CareReportSet { get; set; }
        public virtual DbSet<ActionPlan> ActionPlanSet { get; set; }
    }
}
