//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient : Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Caregiver = new HashSet<Caregiver>();
            this.Doctor = new HashSet<Doctor>();
            this.CareReport = new HashSet<CareReport>();
            this.ActionPlan = new HashSet<ActionPlan>();
            this.CaringRelatives = new HashSet<CaringRelatives>();
        }
    
        public System.DateTime BirthDate { get; set; }
        public string Address { get; set; }
        public string Contactperson { get; set; }
        public string ContactpersonPhone { get; set; }
        public string HealthInsurance { get; set; }
        public int Height { get; set; }
        public double Weight { get; set; }
        public int DegreeOfCare { get; set; }
        public string PowerOfAttorney { get; set; }
    
        public virtual Bio Bio { get; set; }
        public virtual Home Home { get; set; }
        public virtual HealthData HealthData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caregiver> Caregiver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareReport> CareReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionPlan> ActionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaringRelatives> CaringRelatives { get; set; }
    }
}
