//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagerDummy
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitalParameters
    {
        public int VitalParametersID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string TypeOfMeasurement { get; set; }
        public double Value { get; set; }
        public string Unit { get; set; }
        public int HealthDataHealthDataID { get; set; }
    
        public virtual HealthData HealthData { get; set; }
    }
}
